from typing import Dict

location_names : Dict[str, str] = {
    "Abbey_EN" : "Abbey Entrance",
    "Abbey_Cloister_1" : "Abbey Cloister Level 1 Upgrade",
    "Abbey_Cloister_2" : "Abbey Cloister Level 2 Upgrade",
    "Abbey_Cloister_3" : "Abbey Cloister Level 3 Upgrade",
    "Abbey_Cloister_4" : "Abbey Cloister Level 4 Upgrade",
    "Abbey_Cloister_5" : "Abbey Cloister Level 5 Upgrade",
    "Abbey_Cloister_6" : "Abbey Cloister Level 6 Upgrade",
    "Abbey_Transept_1" : "Abbey Transept Level 1 Upgrade",
    "Abbey_Transept_2" : "Abbey Transept Level 2 Upgrade",
    "Abbey_Transept_3" : "Abbey Transept Level 3 Upgrade",
    "Abbey_Transept_4" : "Abbey Transept Level 4 Upgrade",
    "Abbey_Transept_5" : "Abbey Transept Level 5 Upgrade",
    "Abbey_Transept_6" : "Abbey Transept Level 6 Upgrade",
    "Abbey_Penance_Hall_1" : "Abbey Penance Hall Level 1 Upgrade",
    "Abbey_Penance_Hall_2" : "Abbey Penance Hall Level 2 Upgrade",
    "Abbey_Penance_Hall_3" : "Abbey Penance Hall Level 3 Upgrade",
    "Abbey_Penance_Hall_4" : "Abbey Penance Hall Level 4 Upgrade",
    "Abbey_Penance_Hall_5" : "Abbey Penance Hall Level 5 Upgrade",
    "Abbey_Penance_Hall_6" : "Abbey Penance Hall Level 6 Upgrade",
    "Blacksmith_EN" : "Blacksmith Entrance",
    "Blacksmith_Weaponsmithing_1" : "Blacksmith Weaponsmithing Level 1 Upgrade",
    "Blacksmith_Weaponsmithing_2" : "Blacksmith Weaponsmithing Level 2 Upgrade",
    "Blacksmith_Weaponsmithing_3" : "Blacksmith Weaponsmithing Level 3 Upgrade",
    "Blacksmith_Weaponsmithing_4" : "Blacksmith Weaponsmithing Level 4 Upgrade",
    "Blacksmith_Armorsmithing_1" : "Blacksmith Armorsmithing Level 1 Upgrade",
    "Blacksmith_Armorsmithing_2" : "Blacksmith Armorsmithing Level 2 Upgrade",
    "Blacksmith_Armorsmithing_3" : "Blacksmith Armorsmithing Level 3 Upgrade",
    "Blacksmith_Armorsmithing_4" : "Blacksmith Armorsmithing Level 4 Upgrade",
    "Blacksmith_Furnace_1" : "Blacksmith Furnace Level 1 Upgrade",
    "Blacksmith_Furnace_2" : "Blacksmith Furnace Level 2 Upgrade",
    "Blacksmith_Furnace_3" : "Blacksmith Furnace Level 3 Upgrade",
    "Blacksmith_Furnace_4" : "Blacksmith Furnace Level 4 Upgrade",
    "Blacksmith_Furnace_5" : "Blacksmith Furnace Level 5 Upgrade",
    "Guild_EN" : "Guild Entrance",
    "Nomad_Wagon_EN" : "Nomad Wagon Entrance",
    "Sanitarium_EN" : "Sanitarium Entrance",
    "Stagecoach_EN" : "Stagecoach Entrance",
    "Survivalist_EN" : "Survivalist Entrance",
    "Tavern_EN" : "Tavern Entrance",
    "Warrens_EN" : "The Warrens Entrance",
    "Weald_EN" : "The Weald Entrance",
    "Cove_EN" : "The Cove Entrance",
    "Ruins_EN" : "The Ruins Entrance",
    "Darkest_EN" : "The Darkest Dungeon Entrance"
}